extraScrapeConfigs: |
  - job_name: 'k8s-demo'
    metrics_path: /status/v1/prometheus
    scrape_interval: 3s
    static_configs:
      - targets: 
        - http://k8s-demo:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: k8s-demo:8080
