scrape_configs:
  - job_name: 'k8sDemoMetrics'
    metrics_path: '/status/v1/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'kubernetes demo'
