version: "3.9"
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./deployment/datasources:/etc/grafana/provisioning/datasources
