spring:
  application:
    name: k8s-demo

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework: WARN
